x1=int(input("digite el valor de x1:"))
y1=int(input("digite el valor de y1:"))
x2=int(input("digite el valor de x2:"))
y2=int(input("digite el valor de y2:"))
d=((((x1-x2)**2)+((y1-y2)**2))**0.5)
print(d)